//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infoscreen_Verwaltung.classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abteilungen
    {
        public int AbteilungsID { get; set; }
        public string Abteilungsname { get; set; }
        public int StandardBetriebsmode { get; set; }
        public string Abteilungsvorstand { get; set; }
        public string Abteilungswart1 { get; set; }
        public string Abteilungswart2 { get; set; }
        public string Abteilungssprecher { get; set; }
        public Nullable<bool> Samstag { get; set; }
        public string AbteilungsInfo { get; set; }
    }
}
