//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infoscreen_Verwaltung.classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bildschirme
    {
        public int AbteilungsID { get; set; }
        public string Gebäude { get; set; }
        public int Raum { get; set; }
        public int BildschirmID { get; set; }
        public Nullable<int> Anzeigeart { get; set; }
    }
}
