//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infoscreen_Verwaltung.classes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abteilungen> Abteilungen { get; set; }
        public virtual DbSet<Betriebsanzeige> Betriebsanzeige { get; set; }
        public virtual DbSet<Betriebsmodi> Betriebsmodi { get; set; }
        public virtual DbSet<Bildschirme> Bildschirme { get; set; }
        public virtual DbSet<Dateien> Dateien { get; set; }
        public virtual DbSet<Fächer> Fächer { get; set; }
        public virtual DbSet<Gruppenrechte> Gruppenrechte { get; set; }
        public virtual DbSet<Klassen> Klassen { get; set; }
        public virtual DbSet<LehrerTesten1> LehrerTesten1 { get; set; }
        public virtual DbSet<Raeume> Raeume { get; set; }
        public virtual DbSet<Stundenplan> Stundenplan { get; set; }
        public virtual DbSet<Superadmins> Superadmins { get; set; }
        public virtual DbSet<Supplierungen> Supplierungen { get; set; }
        public virtual DbSet<Testarten> Testarten { get; set; }
        public virtual DbSet<Tests> Tests { get; set; }
        public virtual DbSet<Wochentage> Wochentage { get; set; }
    }
}
