//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infoscreen_Verwaltung.classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gruppenrechte
    {
        public int GruppenrechtID { get; set; }
        public string GruppenrechtBezeichnung { get; set; }
        public string Stundenplan { get; set; }
        public string Supplierung { get; set; }
        public string Klasseninfo { get; set; }
        public string Abteilungsinfo { get; set; }
        public string Sprechstunden { get; set; }
        public string Tests { get; set; }
        public string Klassen { get; set; }
        public string Räume { get; set; }
        public string Bildschirme { get; set; }
        public string Gruppenrechte1 { get; set; }
    }
}
