//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infoscreen_Verwaltung.classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klassen
    {
        public int AbteilungsID { get; set; }
        public string Klasse { get; set; }
        public string Klassensprecher { get; set; }
        public string Klasseninfo { get; set; }
        public string Klassenvorstand { get; set; }
    }
}
