//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infoscreen_Verwaltung.classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class LehrerTesten1
    {
        public string LehrerKuerzel { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public string Abteilungen { get; set; }
        public Nullable<int> Sprechstunde { get; set; }
        public Nullable<int> Tag { get; set; }
        public string Gebäude { get; set; }
        public string Raum { get; set; }
        public string Durchwahl { get; set; }
    }
}
