//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infoscreen_Verwaltung.classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tests
    {
        public int AbteilungsID { get; set; }
        public string Klasse { get; set; }
        public string FachKürzel { get; set; }
        public System.DateTime Datum { get; set; }
        public int Stunde { get; set; }
        public int Dauer { get; set; }
        public string LehrerKürzel { get; set; }
        public int TestartID { get; set; }
        public string Raum { get; set; }
    }
}
