//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infoscreen_Verwaltung.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infoscreen_Verwaltung.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die M:U#ddi,1.a7F+1 ähnelt.
        /// </summary>
        internal static string domainPassword {
            get {
                return ResourceManager.GetString("domainPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EL_Infoscreen_AD ähnelt.
        /// </summary>
        internal static string domainUser {
            get {
                return ResourceManager.GetString("domainUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 11 ähnelt.
        /// </summary>
        internal static string maximaleStunden {
            get {
                return ResourceManager.GetString("maximaleStunden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E:\infoscreen\bildschirm_code\presentations\revise.txt ähnelt.
        /// </summary>
        internal static string PfadPowerPointTextDatei {
            get {
                return ResourceManager.GetString("PfadPowerPointTextDatei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0000 ähnelt.
        /// </summary>
        internal static string sandardRaumnummer {
            get {
                return ResourceManager.GetString("sandardRaumnummer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die D:\infoscreen_publish\PPT2PNG\Presentations\ ähnelt.
        /// </summary>
        internal static string speicherort {
            get {
                return ResourceManager.GetString("speicherort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Infoscreen_1.0 ähnelt.
        /// </summary>
        internal static string sql_database {
            get {
                return ResourceManager.GetString("sql_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die yyyy-MM-dd ähnelt.
        /// </summary>
        internal static string sql_datumformat {
            get {
                return ResourceManager.GetString("sql_datumformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die *x-?password-/secure80):passWoRt* ähnelt.
        /// </summary>
        internal static string sql_password {
            get {
                return ResourceManager.GetString("sql_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ELV-SCREEN-2\INFOSCREEN ähnelt.
        /// </summary>
        internal static string sql_server {
            get {
                return ResourceManager.GetString("sql_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SQL_infoscreen ähnelt.
        /// </summary>
        internal static string sql_user {
            get {
                return ResourceManager.GetString("sql_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E:\infoscreen\bildschirm_code\presentations\standard.png ähnelt.
        /// </summary>
        internal static string StandardBild {
            get {
                return ResourceManager.GetString("StandardBild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die htl-md.schule ähnelt.
        /// </summary>
        internal static string standardDomain {
            get {
                return ResourceManager.GetString("standardDomain", resourceCulture);
            }
        }
    }
}
