//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infoscreen_Verwaltung.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infoscreen_Verwaltung.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M:U#ddi,1.a7F+1.
        /// </summary>
        internal static string domainPassword {
            get {
                return ResourceManager.GetString("domainPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EL_Infoscreen_AD.
        /// </summary>
        internal static string domainUser {
            get {
                return ResourceManager.GetString("domainUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        internal static string maximaleStunden {
            get {
                return ResourceManager.GetString("maximaleStunden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E:\infoscreen\bildschirm_code\presentations\revise.txt.
        /// </summary>
        internal static string PfadPowerPointTextDatei {
            get {
                return ResourceManager.GetString("PfadPowerPointTextDatei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000.
        /// </summary>
        internal static string sandardRaumnummer {
            get {
                return ResourceManager.GetString("sandardRaumnummer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E:\infoscreen\bildschirm_code\presentations\.
        /// </summary>
        internal static string speicherort {
            get {
                return ResourceManager.GetString("speicherort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infoscreen_1.0.
        /// </summary>
        internal static string sql_database {
            get {
                return ResourceManager.GetString("sql_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd.
        /// </summary>
        internal static string sql_datumformat {
            get {
                return ResourceManager.GetString("sql_datumformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *x-?password-/secure80):passWoRt*.
        /// </summary>
        internal static string sql_password {
            get {
                return ResourceManager.GetString("sql_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELV-SCREEN-2\INFOSCREEN.
        /// </summary>
        internal static string sql_server {
            get {
                return ResourceManager.GetString("sql_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL_infoscreen.
        /// </summary>
        internal static string sql_user {
            get {
                return ResourceManager.GetString("sql_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E:\infoscreen\bildschirm_code\presentations\standard.png.
        /// </summary>
        internal static string StandardBild {
            get {
                return ResourceManager.GetString("StandardBild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to htl-md.schule.
        /// </summary>
        internal static string standardDomain {
            get {
                return ResourceManager.GetString("standardDomain", resourceCulture);
            }
        }
    }
}
